### ISSUE TITLE
Learn to compile a CCTBX development environment from our fork on Linux

### ISSUE THREAD

**Issue by russell-taylor** [ReliaSolve/cctbx_project#2]
Learn how to build a complete CCTBX development environment that we can use for a test-bed.  It should compile using all of the current libraries used by CCTBX proper but build using the reliasolve/cctbx_project repository.

**Comment by russell-taylor** [comment]
Downloading and running bootstrap.py placed a number of things into a **modules** directory:
- Downloaded scons from zip file
- Cloned boost from cctbx
- Cloned cbflib from yayahjb
- Cloned cctbx_project from cctbx  **@todo Replace this with reliasolve fork in our version.**
- Cloned dxtbx from cctbx
- Fetched updates to dxtbx from dials
- Cloned gui_resources from cctbx
- Cloned ccp4io from cctbx
- Cloned ccp4io_adaptbx from cctbx
- Cloned annlib from cctbx
- Cloned annlib_adaptbx from cctbx
- Cloned tntbx from cctbx
- Cloned clipper from cctbx
- Cloned eigen from cctbx
- Started building dependencies into ./base (also ./base_tmp) directories (alongside modules) from zip sources in gitcdn.link/repo/dials/dependencies/master and other locations: openssl python python_compatibility certifi numpy cython png libsvm pytest pythonextra hdf5 h5py biopython docutils sphinx pyopengl misc lz4_plugin psutil mrcfile freetype matplotlib msgpack pillow gettext glib expat fontconfig render pixman tiff cairo gtk fonts wxpython

Running bootstrap.py with --help describes options:
- Different commands (download, build, ...) default is: hot, update, base, build
- Different packages to be downloaded and configured (molprobity, cctbx, phenix, ...)
- Number of parallel build threads
- complete build output with --verbose
- Reference directory with downloads already done **@todo Perhaps a different way to retarget to our source, by cloning our repository into a modules directory tree in place of the cctbx one.**

**Comment by russell-taylor** [comment]
**@todo Figure out how to compile for Python3 rather than 2.7.18.**

**Comment by russell-taylor** [comment]
Full error message from glib build (made issue on cctbx upstream repository:

```
Installing glib...
  log file is /home/taylorr/rlab/base_tmp/glib_install_log
  getting package glib-2.46.2.tar.gz...
    downloading from http://cci.lbl.gov/cctbx_dependencies/glib-2.46.2.tar.gz : 14.1 MB
    [0%.........20%.........40%.........60%.........80%.........100%]
  installing glib-2.46.2.tar.gz...
Traceback (most recent call last):
  File "modules/cctbx_project/libtbx/auto_build/install_base_packages.py", line 1682, in <module>
    installer(args=sys.argv, log=sys.stdout)
  File "modules/cctbx_project/libtbx/auto_build/install_base_packages.py", line 256, in __init__
    self.build_dependencies(packages=packages)
  File "modules/cctbx_project/libtbx/auto_build/install_base_packages.py", line 782, in build_dependencies
    getattr(self, 'build_%s'%i)()
  File "modules/cctbx_project/libtbx/auto_build/install_base_packages.py", line 1315, in build_glib
    log=pkg_log)
  File "modules/cctbx_project/libtbx/auto_build/install_base_packages.py", line 580, in configure_and_build
    self.call("make -j %d %s" % (nproc, " ".join(list(make_args))), log=log)
  File "modules/cctbx_project/libtbx/auto_build/install_base_packages.py", line 359, in call
    return call(args, log=log, verbose=self.verbose, **kwargs)
  File "/home/taylorr/rlab/modules/cctbx_project/libtbx/auto_build/installer_utils.py", line 55, in call
    raise RuntimeError("Call to '%s' failed with exit code %d" % (args, rc))
RuntimeError: Call to 'make -j 1 ' failed with exit code 2
Process failed with return code 1

```

**Comment by russell-taylor** [comment]
Not described in the instructions is the fact that we should use the `--use-conda` flag to bootstrap.py nowadays.

**Comment by russell-taylor** [comment]
Within bootstrap.py, there is a section for cctbx_module that defines the places to look for it.  Modified it to point at the https:// pull from the reliasolve repository and committed this to the `build-reliasolve-cctbx-project` branch of reliasolve/cctbx_project.  This does indeed pull the source from that repository.

**Comment by russell-taylor** [comment]
We can leave that branch available; it will still presumably pull from master when it actually does the pull, so we'll only use this branch when we want to do the initial build of an environment.

**Comment by russell-taylor** [comment]
Some of the programs that we want to run also require a Phenix installation, which goes into the modules directory.  Phenix can be downloaded from phenix-online.org but it requires a login and password for non-academic users.

**Comment by russell-taylor** [comment]
Once received, this apparently gets installed in the module directory.

**Comment by russell-taylor** [comment]
Conda-based install on Windows should go something like this:

```
<miniconda3 installation>/Scripts/activate base
conda create -n test -c conda-forge cctbx-base
conda activate test
python
```
