### ISSUE TITLE
Reduce2 now requires Phenix phaser to run

### ISSUE THREAD

**Issue by russell-taylor** [ReliaSolve/cctbx_project#275]
When run without C:\tmp\cctbx_phenix\modules\phaser in PYTHONPATH:

```
Traceback (most recent call last):
  File "c:\program files\microsoft visual studio\2022\community\common7\ide\extensions\microsoft\python\profiling\proflaun.py", line 35, in <module>
    vspyprof.profile(__file__, globals(), locals(), profdll)
  File "c:\program files\microsoft visual studio\2022\community\common7\ide\extensions\microsoft\python\profiling\vspyprof.py", line 87, in profile
    exec(code, globals_obj, locals_obj)
  File "C:\Users\taylorr\source\repos\MolProbityPython\MolProbityPython\reduce2.py", line 4, in <module>
    from mmtbx.programs import reduce2
  File "C:\tmp\cctbx_phenix\modules\cctbx_project\mmtbx\programs\reduce2.py", line 25, in <module>
    from mmtbx.probe import Helpers
  File "C:\tmp\cctbx_phenix\modules\cctbx_project\mmtbx\probe\Helpers.py", line 25, in <module>
    import iotbx.map_model_manager
  File "C:\tmp\cctbx_phenix\modules\cctbx_project\iotbx\map_model_manager.py", line 12, in <module>
    from mmtbx.model import manager as model_manager
  File "C:\tmp\cctbx_phenix\modules\cctbx_project\mmtbx\model\__init__.py", line 3, in <module>
    from mmtbx.model.model import *
  File "C:\tmp\cctbx_phenix\modules\cctbx_project\mmtbx\model\model.py", line 33, in <module>
    import mmtbx.hydrogens
  File "C:\tmp\cctbx_phenix\modules\cctbx_project\mmtbx\hydrogens\__init__.py", line 2, in <module>
    from mmtbx.utils import rotatable_bonds
  File "C:\tmp\cctbx_phenix\modules\cctbx_project\mmtbx\utils\__init__.py", line 41, in <module>
    from mmtbx.twinning import twin_f_model
  File "C:\tmp\cctbx_phenix\modules\cctbx_project\mmtbx\twinning\twin_f_model.py", line 21, in <module>
    import mmtbx.f_model
  File "C:\tmp\cctbx_phenix\modules\cctbx_project\mmtbx\f_model\__init__.py", line 3, in <module>
    from mmtbx.f_model.f_model import *
  File "C:\tmp\cctbx_phenix\modules\cctbx_project\mmtbx\f_model\f_model.py", line 36, in <module>
    import mmtbx.refinement.targets
  File "C:\tmp\cctbx_phenix\modules\cctbx_project\mmtbx\refinement\targets.py", line 6, in <module>
    import phaser.phenix_adaptors.sad_target
ModuleNotFoundError: No module named 'phaser.phenix_adaptors'
```

**Comment by russell-taylor** [comment]
Phaser may be available for download without a Phenix login...

**Comment by russell-taylor** [comment]
It should be the case that PHASER is not in my modules place -- there should not be a module/phasers.  In a clean CCTBX build, this should not happen.

**Comment by russell-taylor** [comment]
In a clean CCTBX build, Phaser is indeed not imported.
