### ISSUE TITLE
Nigel reports test failure after changes

### ISSUE THREAD

**Issue by russell-taylor** [ReliaSolve/cctbx_project#277]
Russell

I made some changes that have caused

modules/cctbx_project/mmtbx/regression/tst_reduce.py

to fail. Would you like taking a quick look to see if I've messed it all up or it's just a small adjustment? 

Cheers

Nigel

**Comment by russell-taylor** [comment]
This runs without failure on the master branch of cctbx_project on 11/28/2023 when I didn't rebuild. It also works after rebuilding with bootstrap.py.

**Comment by russell-taylor** [comment]
Nigel reports the following: 
I made some big changes to the GeoStd which seemed to correspond with the fail so maybe check that you have an updated GeoStd repo in the chem_data directory. However, the output seems to point to a c++ issue. This is the output from the overnight testing.

```
libtbx.python "/dev/shm/bkpoon/software/phenix-clean/modules/cctbx_project/mmtbx/regression/tst_reduce.py" [FAIL] 6.0s
  Time:  5.99
  Return code: 1
  OKs: 0
  Standard error:
    /dev/shm/bkpoon/software/phenix-clean/conda_base/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: to-Python converter for scitbx::af::shared<scitbx::af::shared<bool> > already registered; second conversion method ignored.
      return f(*args, **kwds)
    Traceback (most recent call last):
      File "/dev/shm/bkpoon/software/phenix-clean/modules/cctbx_project/mmtbx/regression/tst_reduce.py", line 505, in <module>
        ret = RunReduceTests()
      File "/dev/shm/bkpoon/software/phenix-clean/modules/cctbx_project/mmtbx/regression/tst_reduce.py", line 52, in RunReduceTests
        assert (len(ret) == 0), 'len(ret)=%s' % len(ret)
    AssertionError: len(ret)=81
```

**Comment by russell-taylor** [comment]
I'm stuck trying to build a new version of phenix. Asked Billy about the error message I'm getting after updating and retrying. Billy reports the following: It's because of Boost. If you're on Windows, you can delete the modules/boost directory. There is a Boost dependency in the conda environment. For future bootstrap updates, you can add the --no-boost-src flag so that Boost is no longer added to your modules directory. You will also have to delete your existing "build" directory to get rid of anything Boost related.

**Comment by russell-taylor** [comment]
The rebuilt version does fail, inside Optimizers.py, line 2028. This is in the following: "Optimizers.Test(): Incorrect number of Movers for single-hydrogen rotator test:"; this is now adding 3 rather than 1 rotators in the two (SER and VAL) residues from 7c31 used in the test. So it looks like it is either adding two new rotatable hydrogens that were not before placed or else it is marking two as rotatable that were not before.

**Comment by russell-taylor** [comment]
These are lone hydrogens that can now be placed on the terminus on each residue. This is adding rotatable hydrogens, which breaks the tests that count the number of added Movers. It also broke the angle-parsing code.

Fixed and pushed commits to master.
