### ISSUE TITLE
Check the new version of SuiteName running against CIF files

### ISSUE THREAD

**Issue by russell-taylor** [ReliaSolve/cctbx_project#77]

**Comment by russell-taylor** [comment]
@Joymaker Running `phenix.suitename -string 1hhx.pdb` works but running `phenix.suitename -string 1hhx.cif` fails with the following:
```
Traceback (most recent call last):
  File "/home/taylorr/rlab/cctbx_reliasolve/build/../modules/cctbx_project/mmtbx/command_line/suitename.py", line 10, in <module>
    suitename.run(args=sys.argv[1:])
  File "/home/taylorr/rlab/cctbx_reliasolve/modules/cctbx_project/mmtbx/programs/suitename.py", line 64, in run
    main(optionsIn=options)
  File "/home/taylorr/rlab/cctbx_reliasolve/modules/cctbx_project/mmtbx/suitename/suitename.py", line 80, in main
    suites = read(inFile)
  File "/home/taylorr/rlab/cctbx_reliasolve/modules/cctbx_project/mmtbx/suitename/suitename.py", line 99, in read
    residues = readResidues(inFile)
  File "/home/taylorr/rlab/cctbx_reliasolve/modules/cctbx_project/mmtbx/suitename/suiteninput.py", line 82, in readResidues
    baseCode = fields[options.pointidfields - 1]
IndexError: list index out of range
```

**Comment by russell-taylor** [comment]
The code seems to be doing its own PDB parsing rather than letting the Program Template do the reading or even using the CCTBX file reader.  To enable future-proof reading, it should be using the PDB/CIF reader and then walking the appropriate conformer in the hierarchy that it reads in.

The custom parser can be used for dangle and mp_geo inputs but should not be used for PDB or mmCIF files.

**Comment by russell-taylor** [comment]
Re-test when issue https://github.com/ReliaSolve/cctbx_project/issues/82 has been resolved and we're reading the files using the CCTBX reader.

**Comment by russell-taylor** [comment]
Issue 82 was resolved by telling suitename to read cif files as PDB files.  This turned up another difference, described in https://github.com/ReliaSolve/cctbx_project/issues/83

Retry more files once that issue is resolved.
